server:
  port: 8081

spring:
  datasource:
    initialization-mode: always # Always initialize
    url: jdbc:mysql://localhost:3306/small_project?useSSL=false
    username: root
    password: 123456

  jpa:
    generate-ddl: true # Enable jpa generation
    hibernate:
      ddl-auto: none # NO Hibernate generation
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true # default setting to remove warning